routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\BlogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PageController::class, 'index']);
Route::get('blog/{slug}', [PageController::class, 'blog']);
Route::get('/search', [PageController::class, 'search'])->name('search');;

Auth::routes();

Route::group(['middleware' => ['auth']], function() {
    Route::resource('users', UserController::class);
    Route::get('home', [HomeController::class, 'index'])->name('home');
});
Route::get('/users/create', [UserController::class, 'create'])->name('users.create')->middleware('role:admin');
Route::get('/users/{user}/edit', [UserController::class, 'edit'])->name('users.edit')->middleware('role:admin');
Route::resource('blogs', BlogController::class)->middleware('role:admin');

resources/views/blog.blade.php
@extends('layouts.front')
@section('content')
<!-- page title -->
<section class="page-title bg-primary position-relative">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h1 class="text-white font-tertiary">Blogs</h1>
      </div>
    </div>
  </div>
  <!-- background shapes -->
  <img src="{{url('assets/front/images/illustrations/page-title.png')}}" alt="illustrations" class="bg-shape-1 w-100">
  <img src="{{url('assets/front/images/illustrations/leaf-pink-round.png')}}" alt="illustrations" class="bg-shape-2">
  <img src="{{url('assets/front/images/illustrations/dots-cyan.png')}}" alt="illustrations" class="bg-shape-3">
  <img src="{{url('assets/front/images/illustrations/leaf-orange.png')}}" alt="illustrations" class="bg-shape-4">
  <img src="{{url('assets/front/images/illustrations/leaf-yellow.png')}}" alt="illustrations" class="bg-shape-5">
  <img src="{{url('assets/front/images/illustrations/dots-group-cyan.png')}}" alt="illustrations" class="bg-shape-6">
  <img src="{{url('assets/front/images/illustrations/leaf-cyan-lg.png')}}" alt="illustrations" class="bg-shape-7">
</section>
<section class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h3 class="font-tertiary mb-3">{{$blog->title}}</h3>
        <p class="font-secondary mb-5">Published on {{date("F j, Y",strtotime($blog->created_at))}} by <span class="text-primary">uixgeek</span
            class="text-primary"> on <span>UX design</span></p>
        <div class="content">
          <img src="{{url('assets/front/images/blog/post-1.jpg')}}" alt="post-thumb" class="img-fluid rounded float-left mr-5 mb-4">
          {!!$blog->content!!}
        </div>
      </div>
    </div>
  </div>
</section>
@endsection

resources/views/footer.blade.php
<!-- partial:partials/_footer.html -->
<footer class="footer">
  <div class="d-sm-flex justify-content-center justify-content-sm-between">
    <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2021.  Premium <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap admin template</a> from BootstrapDash. All rights reserved.</span>
    <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="ti-heart text-danger ml-1"></i></span>
  </div>
</footer>

resources/views/header.blade.php
<!-- BEGIN: Header -->
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
  <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
    <a class="navbar-brand brand-logo mr-5" href="index.html"><img src="{{url('assets/images/logo.svg')}}" class="mr-2" alt="logo"/></a>
    <a class="navbar-brand brand-logo-mini" href="index.html"><img src="{{url('assets/images/logo-mini.svg')}}" alt="logo"/></a>
  </div>
  <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
      <span class="icon-menu"></span>
    </button>
    <ul class="navbar-nav mr-lg-2">
      <li class="nav-item nav-search d-none d-lg-block">
        <div class="input-group">
          <div class="input-group-prepend hover-cursor" id="navbar-search-icon">
            <span class="input-group-text" id="search">
              <i class="icon-search"></i>
            </span>
          </div>
          <input type="text" class="form-control" id="navbar-search-input" placeholder="Search now" aria-label="search" aria-describedby="search">
        </div>
      </li>
    </ul>
    <ul class="navbar-nav navbar-nav-right">
      <li class="nav-item dropdown">
        <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
          <i class="icon-bell mx-0"></i>
          <span class="count"></span>
        </a>
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
          <p class="mb-0 font-weight-normal float-left dropdown-header">Notifications</p>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-success">
                <i class="ti-info-alt mx-0"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <h6 class="preview-subject font-weight-normal">Application Error</h6>
              <p class="font-weight-light small-text mb-0 text-muted">
                Just now
              </p>
            </div>
          </a>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-warning">
                <i class="ti-settings mx-0"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <h6 class="preview-subject font-weight-normal">Settings</h6>
              <p class="font-weight-light small-text mb-0 text-muted">
                Private message
              </p>
            </div>
          </a>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-info">
                <i class="ti-user mx-0"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <h6 class="preview-subject font-weight-normal">New user registration</h6>
              <p class="font-weight-light small-text mb-0 text-muted">
                2 days ago
              </p>
            </div>
          </a>
        </div>
      </li>
      <li class="nav-item nav-profile dropdown">
        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
          <img src="{{url('assets/images/faces/face28.jpg')}}" alt="profile"/>
        </a>
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
          <a class="dropdown-item">
            <i class="ti-settings text-primary"></i>
            Settings
          </a>
          <a class="dropdown-item" href="{{route('logout')}}"  onclick="event.preventDefault();
                         document.getElementById('logout-form').submit();">

            <i class="ti-power-off text-primary"></i>
            Logout
          </a>
          <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
              @csrf
          </form>
        </div>
      </li>
      <li class="nav-item nav-settings d-none d-lg-flex">
        <a class="nav-link" href="#">
          <i class="icon-ellipsis"></i>
        </a>
      </li>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
      <span class="icon-menu"></span>
    </button>
  </div>
</nav>
<!-- END: Header -->

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
  <div class="row">
    <div class="col-md-12 grid-margin">
      <div class="row">
        <div class="col-12 col-xl-8 mb-4 mb-xl-0">
          <h3 class="font-weight-bold">Welcome {{Auth::user()->name;}}</h3>
          
        </div>
       
      </div>
    </div>
  </div>

@endsection

resources/views/index.blade.php
@extends('layouts.front')
@section('content')
<!-- page title -->
<section class="page-title bg-primary position-relative">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h1 class="text-white font-tertiary">Blogs</h1>
      </div>
    </div>
  </div>
  <!-- background shapes -->
  <img src="{{url('assets/front/images/illustrations/page-title.png')}}" alt="illustrations" class="bg-shape-1 w-100">
  <img src="{{url('assets/front/images/illustrations/leaf-pink-round.png')}}" alt="illustrations" class="bg-shape-2">
  <img src="{{url('assets/front/images/illustrations/dots-cyan.png')}}" alt="illustrations" class="bg-shape-3">
  <img src="{{url('assets/front/images/illustrations/leaf-orange.png')}}" alt="illustrations" class="bg-shape-4">
  <img src="{{url('assets/front/images/illustrations/leaf-yellow.png')}}" alt="illustrations" class="bg-shape-5">
  <img src="{{url('assets/front/images/illustrations/dots-group-cyan.png')}}" alt="illustrations" class="bg-shape-6">
  <img src="{{url('assets/front/images/illustrations/leaf-cyan-lg.png')}}" alt="illustrations" class="bg-shape-7">

</section>
<!-- /page title -->

<!-- blog -->
<section class="section">
  <div class="container">
  <form action="{{ route('search') }}" class="row" method="GET">
            <div class="col-md-3">
              <input type="text" id="name"  name="search" placeholder="Search" class="form-control px-0 mb-4">
            </div>
            <div class="col-lg-2">
              <button class="btn btn-primary w-100" type="submit">Search</button>
            </div>
          </form>
    <div class="row">
      @foreach($blogs as $blog)
        <div class="col-lg-4 col-sm-6 mb-4">
          <article class="card shadow">
            <img class="rounded card-img-top" src="{{url('assets/front/images/blog/post-5.jpg')}}" alt="post-thumb">
            <div class="card-body">
              <h4 class="card-title"><a class="text-dark" href="{{url('blog',$blog->slug)}}">{{$blog->title}}</a>
              </h4>
              <p class="cars-text">{{$blog->short_description}}</p>
              <h6 class="card-title">Category:{{$blog->blog_cat->title}}</h6>
              <a href="{{url('blog',$blog->slug)}}" class="btn btn-xs btn-primary">Read More</a>
            </div>
          </article>
        </div>
    @endforeach
    </div>
    {{-- Pagination --}}
        <div class="d-flex justify-content-center">
            {!! $blogs->links() !!}
        </div>
  </div>
</section>
<!-- /blog -->
@endsection

resources/views/search.blade.php
@extends('layouts.front')
@section('content')
<!-- page title -->
<section class="page-title bg-primary position-relative">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h1 class="text-white font-tertiary">Blogs</h1>
      </div>
    </div>
  </div>
  <!-- background shapes -->
  <img src="{{url('assets/front/images/illustrations/page-title.png')}}" alt="illustrations" class="bg-shape-1 w-100">
  <img src="{{url('assets/front/images/illustrations/leaf-pink-round.png')}}" alt="illustrations" class="bg-shape-2">
  <img src="{{url('assets/front/images/illustrations/dots-cyan.png')}}" alt="illustrations" class="bg-shape-3">
  <img src="{{url('assets/front/images/illustrations/leaf-orange.png')}}" alt="illustrations" class="bg-shape-4">
  <img src="{{url('assets/front/images/illustrations/leaf-yellow.png')}}" alt="illustrations" class="bg-shape-5">
  <img src="{{url('assets/front/images/illustrations/dots-group-cyan.png')}}" alt="illustrations" class="bg-shape-6">
  <img src="{{url('assets/front/images/illustrations/leaf-cyan-lg.png')}}" alt="illustrations" class="bg-shape-7">

</section>
<!-- /page title -->

<!-- blog -->
<section class="section">
  <div class="container">
  <form action="{{ route('search') }}" class="row" method="GET">
            <div class="col-md-3">
              <input type="text" id="name" name="search" value="{{$data['search']}}" placeholder="Search" class="form-control px-0 mb-4">
            </div>
            <div class="col-lg-2">
              <button class="btn btn-primary w-100" type="submit">Search</button>
            </div>
          </form>
          @if($blogs->isNotEmpty())
    <div class="row">
      @foreach($blogs as $blog)
        <div class="col-lg-4 col-sm-6 mb-4">
          <article class="card shadow">
            <img class="rounded card-img-top" src="{{url('assets/front/images/blog/post-5.jpg')}}" alt="post-thumb">
            <div class="card-body">
              <h4 class="card-title"><a class="text-dark" href="{{url('blog',$blog->slug)}}">{{$blog->title}}</a>
              </h4>
              <p class="cars-text">{{$blog->short_description}}</p>
              <h6 class="card-title">Category:{{$blog->blog_cat->title}}</h6>
              <a href="{{url('blog',$blog->slug)}}" class="btn btn-xs btn-primary">Read More</a>
            </div>
          </article>
        </div>
    @endforeach
    </div>
    @else 
    <div class="row">
        <h2>No posts found</h2>
    </div>
@endif
    {{-- Pagination --}}
        <div class="d-flex justify-content-center">
            {{ $blogs->appends($data)->links() }}
        </div>
  </div>
</section>
<!-- /blog -->
@endsection

resources/views/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
 
  <ul class="nav">
    <li class="nav-item">
            <a class="nav-link" href="{{url('/home')}}">
              <i class="icon-grid menu-icon"></i>
              <span class="menu-title">Dashboard</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
              <i class="icon-layout menu-icon"></i>
              <span class="menu-title">Blog</span>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="ui-basic">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"> <a class="nav-link" href="{{ route('blogs.index') }}">list</a></li>
                @hasrole('admin')
                <li class="nav-item"> <a class="nav-link" href="{{ route('blogs.create') }}">Add</a></li>
                @endhasrole
              </ul>
            </div>
          </li>
  </ul>
</nav>