routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\BlogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PageController::class, 'index']);
Route::get('blog/{slug}', [PageController::class, 'blog']);
Route::get('/search', [PageController::class, 'search'])->name('search');;

Auth::routes();

Route::group(['middleware' => ['auth']], function() {
    Route::resource('users', UserController::class);
    Route::get('home', [HomeController::class, 'index'])->name('home');
});
Route::get('/users/create', [UserController::class, 'create'])->name('users.create')->middleware('role:admin');
Route::get('/users/{user}/edit', [UserController::class, 'edit'])->name('users.edit')->middleware('role:admin');
Route::resource('blogs', BlogController::class)->middleware('role:admin');

resources/views/employee/create.blade.php
@extends('layouts.app')
@section('content')
<div class="content-wrapper">
  <div class="row">
    <div class="col-md-10 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Add Employee</h4>
          <p class="card-description">
            Add Employee
          </p>
       
            <form method="post" action="{{ route('users.store') }}" class="forms-sample employee">
        @csrf
            <div class="form-group">
              <label for="exampleInputUsername1">Name</label>
              <input type="text" name="name" value="{{ old('name') }}" class="form-control" id="exampleInputUsername1" placeholder="Name">
             

                <span class="text-danger">
                
                </span>
            
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Email</label>
              <input type="email" name="email" value="{{ old('email') }}" class="form-control"  placeholder="Email">
           

                <span class="text-danger">
               
                </span>
              
            </div>
          
         
            <div class="form-group">
              <label for="exampleInputPassword1">Password</label>
              <input type="password" class="form-control" name="password" id="exampleInputPassword1" placeholder="Password">
          
              <span class="text-danger">

         
              </span>
             
            </div>
            <div class="form-group">
              <label for="exampleInputConfirmPassword1">Confirm Password</label>
              <input type="password" class="form-control" name="password_confirmation"  id="exampleInputConfirmPassword1" placeholder="Password">
            
              <span class="text-danger">
               
               </span>
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Building</label>
              <input type="number" name="building_no" value="{{ old('building_no') }}" class="form-control"  placeholder="Building no">
           
              <span class="text-danger">
               
               </span>
            </div><div class="form-group">
              <label for="street_name">Street Name</label>
              <input type="text" name="street_name" value="{{ old('street_name') }}" class="form-control"  placeholder="Email">
           
              <span class="text-danger">
               
               </span>
            </div>
            <div class="form-group">
              <label for="city">City</label>
              <input type="text" name="city" value="{{ old('city') }}" class="form-control"  placeholder="City">
             
              <span class="text-danger">
               
               </span>
            </div>
            <div class="form-group">
              <label for="city">State</label>
              <input type="text" name="state" value="{{ old('state') }}" class="form-control"  placeholder="State">
             
              <span class="text-danger">
               
               </span>
            </div><div class="form-group">
              <label for="city">Country</label>
              <input type="text" name="country" value="{{ old('country') }}" class="form-control"  placeholder="Country">
             
              <span class="text-danger">
               
               </span>
            </div><div class="form-group">
              <label for="city">Pincode</label>
              <input type="text" name="pincode" value="{{ old('pincode') }}" class="form-control"  placeholder="Pincode">
             
              <span class="text-danger">
               
               </span>
            </div>
            <button type="submit" class="btn btn-primary mr-2">Submit</button>

          </form>
        </div>
      </div>
    </div>

  </div>
</div>

@endsection

resources/views/employee/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="content-wrapper">
  <div class="row">
    <div class="col-md-10 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Edit Employee</h4>
          <p class="card-description">
            Add Employee
          </p>
       
            <form method="post" action="{{ route('users.update',$user->id) }}" class="forms-sample employee">  
        @csrf
        @method('PUT')
            <div class="form-group">
              <label for="exampleInputUsername1">Name</label>
              <input type="text" name="name" value="{{$user->name}}" class="form-control" id="exampleInputUsername1" placeholder="Name">
             

                <span class="text-danger">
                
                </span>
            
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Email</label>
              <input type="email" name="email" value="{{$user->email}}" class="form-control"  placeholder="Email" disabled>
           

                <span class="text-danger">
               
                </span>
              
            </div>
          
         
           
            <div class="form-group">
              <label for="exampleInputEmail1">Building</label>
              <input type="number" name="building_no" value="{{$user->address->building_no}}" class="form-control"  placeholder="Building no">
           
              <span class="text-danger">
               
               </span>
            </div><div class="form-group">
              <label for="street_name">Street Name</label>
              <input type="text" name="street_name" value="{{$user->address->street_name}}" class="form-control"  placeholder="Email">
           
              <span class="text-danger">
               
               </span>
            </div>
            <div class="form-group">
              <label for="city">City</label>
              <input type="text" name="city" value="{{$user->address->city}}" class="form-control"  placeholder="City">
             
              <span class="text-danger">
               
               </span>
            </div>
            <div class="form-group">
              <label for="city">State</label>
              <input type="text" name="state" value="{{$user->address->state}}" class="form-control"  placeholder="State">
             
              <span class="text-danger">
               
               </span>
            </div><div class="form-group">
              <label for="city">Country</label>
              <input type="text" name="country" value="{{$user->address->country}}" class="form-control"  placeholder="Country">
             
              <span class="text-danger">
               
               </span>
            </div><div class="form-group">
              <label for="city">Pincode</label>
              <input type="text" name="pincode" value="{{$user->address->pincode}}" class="form-control"  placeholder="Pincode">
             
              <span class="text-danger">
               
               </span>
            </div>
            <button type="submit" class="btn btn-primary mr-2">Submit</button>

          </form>
        </div>
      </div>
    </div>

  </div>
</div>

@endsection

resources/views/employee/index.blade.php
@extends('layouts.app')
@section('content')
<div class="content-wrapper">
  <div class="row">

    <div class="col-lg-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
        <h2 class="pull-left">Employee Management</h2>
        @hasrole('admin')
                <a class="btn btn-success text-right mb-3" href="{{ route('users.create') }}"> Create New Employee</a>
                @endhasrole
          <div class="table-responsive">
          <table class="table table-bordered">
             <tr>
               <th>No</th>
               <th>Name</th>
               <th>Email</th>
               <th>Roles</th>
               <th width="280px">Action</th>
             </tr>
             @foreach ($users as $key => $user)
              <tr>
                <td>{{ ++$key }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>
                  @if(!empty($user->getRoleNames()))
                    @foreach($user->getRoleNames() as $role)
                       <label class="badge badge-success">{{ $role }}</label>
                    @endforeach
                  @endif
                </td>
                <td>
                @hasrole('admin')
                   <a class="btn btn-primary" href="{{ route('users.edit',$user->id) }}">Edit</a>
                   @endhasrole
                    <!-- {!! Form::open(['method' => 'DELETE','route' => ['users.destroy', $user->id],'style'=>'display:inline']) !!}
                        {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                    {!! Form::close() !!} -->
                </td>
              </tr>
             @endforeach
            </table>
            {{-- Pagination --}}
            <div class="d-flex justify-content-center">
              
            </div>
          </div>
        </div>
      </div>
    </div>


  </div>
</div>
@endsection