routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\BlogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PageController::class, 'index']);
Route::get('blog/{slug}', [PageController::class, 'blog']);
Route::get('/search', [PageController::class, 'search'])->name('search');;

Auth::routes();

Route::group(['middleware' => ['auth']], function() {
    Route::resource('users', UserController::class);
    Route::get('home', [HomeController::class, 'index'])->name('home');
});
Route::get('/users/create', [UserController::class, 'create'])->name('users.create')->middleware('role:admin');
Route::get('/users/{user}/edit', [UserController::class, 'edit'])->name('users.edit')->middleware('role:admin');
Route::resource('blogs', BlogController::class)->middleware('role:admin');

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Blog extends Model
{
    use HasFactory;
    use Sluggable;

    protected $fillable = [
        'title',
        'short_description',
        'content',
        'category_id',
        'status',
    ];

    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    public function blog_cat()
    {
        return $this->belongsTo(BlogCategory::class,'category_id');
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use App\Models\BlogCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;
use Validator;
use Auth;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blogs = Blog::with('blog_cat')->paginate(10);
        return view('blog.index')->with([
            'blogs'  => $blogs
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = BlogCategory::pluck('title','id')->all();
        return view('blog.create', compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'category_id'=>'required'
        ]);

            $request->status = $request->status =='on'? 1 :0;

        $blog = new Blog;
        $blog->title = $request->title;
        $blog->short_description = $request->short_description;
        $blog->content = $request->content;
        $blog->category_id = $request->category_id;
        $blog->status = $request->status;
        $blog->save();


        return redirect('blogs')->with('success','New Record Add Successfully.....');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $blog = Blog::where('id',$id)->first();
        $category = BlogCategory::pluck('title','id')->all();
        return view('blog.edit', compact('blog','category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required',
            'category_id'=>'required'
        ]);

            $request->status = $request->status =='on'? 1 :0;

        $blog = Blog::find($id);
        $blog->title = $request->title;
        $blog->short_description = $request->short_description;
        $blog->content = $request->content;
        $blog->category_id = $request->category_id;
        $blog->status = $request->status;
        $blog->save();
        return redirect('blogs')->with('success','Update Successfully.....');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/blog/create.blade.php
@extends('layouts.app')
@section('content')
<div class="content-wrapper">
  <div class="row">
    <div class="col-md-10 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Add Blog</h4>
          <p class="card-description">
            Add Blog
          </p>
       
            <form method="post" action="{{ route('blogs.store') }}" class="forms-sample">
        @csrf
            <div class="form-group">
              <label for="exampleInputUsername1">Title</label>
              <input type="text" name="title" value="{{ old('title') }}" class="form-control" id="exampleInputUsername1" placeholder="Name">
              @if ($errors->has('title'))

          <span class="text-danger">
          {{ $errors->first('title') }}
          </span>
          @endif
                      
            </div>
           
            <div class="form-group">
              <label for="exampleInputEmail1">Blog Category</label>
             <select class="form-control" name="category_id">
               <option value="">Select</option>
               @foreach($category as $k=>$cat)
               <option value="{{$k}}" {{ old('category_id') == $k ? 'selected' : '' }}>{{$cat}}</option>
               @endforeach
             </select>
             @if ($errors->has('category_id'))
             <span class="text-danger">
          {{ $errors->first('category_id') }}
          </span>
          @endif
        
            </div>
            
            <div class="form-group">
              <label for="short_description">Short Description</label>
              <input type="text" name="short_description" value="{{ old('short_description') }}" class="form-control"  placeholder="Short Description">
           
              <span class="text-danger">
               
               </span>
            </div>
            <div class="form-group">
              <label for="city">Description</label>
              <textarea name="content" class="form-control"  placeholder="Description">{{ old('content') }}</textarea>
             
              <span class="text-danger">
               
               </span>
            </div>
            
            <div class="form-group">               
                          <div class="form-check form-check-success">
                            <label class="form-check-label">
                              <input type="checkbox" name="status" class="form-check-input" {{old('status')=='on' ? 'checked':'';}}>
                              Status
                            <i class="input-helper"></i></label>
                          </div>
                        </div>
            <button type="submit" class="btn btn-primary mr-2">Submit</button>

          </form>
        </div>
      </div>
    </div>

  </div>
</div>

@endsection

resources/views/blog/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="content-wrapper">
  <div class="row">
    <div class="col-md-10 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Edit Blog</h4>
          <p class="card-description">
          Edit Blog
          </p>
       
            <form method="post" action="{{ route('blogs.update',$blog->id) }}" class="forms-sample">  
        @csrf
        @method('PUT')
        <div class="form-group">
              <label for="exampleInputUsername1">Title</label>
              <input type="text" name="title" value="{{ $blog->title }}" class="form-control" id="exampleInputUsername1" placeholder="Name">
              @if ($errors->has('title'))

          <span class="text-danger">
          {{ $errors->first('title') }}
          </span>
          @endif
                      
            </div>
           
            <div class="form-group">
              <label for="exampleInputEmail1">Blog Category</label>
             <select class="form-control" name="category_id">
               <option value="">Select</option>
               @foreach($category as $k=>$cat)
               <option value="{{$k}}" {{ $blog->category_id == $k ? 'selected' : '' }}>{{$cat}}</option>
               @endforeach
             </select>
             @if ($errors->has('category_id'))
             <span class="text-danger">
          {{ $errors->first('category_id') }}
          </span>
          @endif
        
            </div>
            
            <div class="form-group">
              <label for="short_description">Short Description</label>
              <input type="text" name="short_description"  class="form-control"  value="{{ $blog->short_description }}" placeholder="Short Description">
           
              <span class="text-danger">
               
               </span>
            </div>
            <div class="form-group">
              <label for="city">Description</label>
              <textarea name="content" class="form-control"  placeholder="Description">{{ $blog->content }}</textarea>
             
              <span class="text-danger">
               
               </span>
            </div>
            
            <div class="form-group">               
                          <div class="form-check form-check-success">
                            <label class="form-check-label">
                              <input type="checkbox" name="status" class="form-check-input" {{$blog->status==1 ? 'checked':'';}}>
                              Status
                            <i class="input-helper"></i></label>
                          </div>
                        </div>
            <button type="submit" class="btn btn-primary mr-2">Submit</button>

          </form>
        </div>
      </div>
    </div>

  </div>
</div>

@endsection

resources/views/blog/index.blade.php
@extends('layouts.app')
@section('content')
<div class="content-wrapper">
  <div class="row">

    <div class="col-lg-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
        <h2 class="pull-left">Blogs</h2>
        @hasrole('admin')
                <a class="btn btn-success text-right mb-3" href="{{ route('blogs.create') }}"> Add Blog</a>
                @endhasrole
          <div class="table-responsive">
          <table class="table table-bordered">
             <tr>
               <th>No</th>
               <th>Title</th>
               <th>Short Description</th>
               <th>Status</th>
               <th>Created</th>
               <th width="280px">Action</th>
             </tr>
             @foreach ($blogs as $key => $blog)
              <tr>
                <td>{{ ++$key }}</td>
                <td>{{ $blog->title }}</td>
                <td>{{ $blog->short_description }}</td>
                <td>{{ $blog->status==1 ? 'Active':'Deactive' }}</td>
                <td>
                {{date("Y-m-d",strtotime($blog->created_at))}}
                </td>
                <td>
                @hasrole('admin')
                   <a class="btn btn-primary" href="{{ route('blogs.edit',$blog->id) }}">Edit</a>
                   @endhasrole
                   
                </td>
              </tr>
             @endforeach
            </table>
            {{-- Pagination --}}
            <div class="d-flex justify-content-center">
            {!! $blogs->links() !!}
            </div>
          </div>
        </div>
      </div>
    </div>


  </div>
</div>
@endsection